Abstract Chunk Management
monstercat/golib pull request #83
Opened 2023-01-10 21:20 UTC by bryancua

Previously, chunked uploading was provided only for S3. This commit extracts the chunking operations from the API calls that perform the actual upload.

https://app.asana.com/0/0/1203422151655933/f

2023-01-10 23:33 UTC, Chris0296 approved these changes

2023-01-10 23:52 UTC, MenadeL approved these changes

2023-01-11 00:22 UTC, tmathews commented
PR is big enough to warrant a meeting review to explain it. Schedule one for tomorrow please.

2023-01-11 00:24 UTC, tmathews requested changes
I also disagree with breaking APIs by deleting them. Simply place deprecation notices please.

2023-01-11 00:26 UTC, bryancua commented
> I also disagree with breaking APIs by deleting them. Simply place deprecation notices please.

Functions weren't deleted. They were moved into data.ChunkFileService.

2023-01-11 19:05 UTC, tmathews approved these changes

2023-01-11 19:47 UTC, merged